//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BharaDibo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int OrderID { get; set; }
        public string itemName { get; set; }
        public int totalPrice { get; set; }
        public string cusEmail { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
    }
}
