//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BharaDibo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PRID { get; set; }
        public string PRName { get; set; }
        public string PRImage { get; set; }
        public string PRType { get; set; }
        public string PRDescription { get; set; }
        public Nullable<decimal> PRPrize { get; set; }
        public Nullable<decimal> PRRating { get; set; }
        public Nullable<int> PRQuantity { get; set; }
    }
}
